baseURL = 'http://kn100.me/'
languageCode = 'en-gb'
title = 'Kevin Norman'
theme = "ananke"
googleAnalytics = "UA-116596166-1"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pluralizelisttitles = "false"

[permalinks]
  posts = "/:slug"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  text_color = ""
  author = "Kevin Norman"
  favicon = "/site-resources/logonotext.png"
  site_logo = "/site-resources/logonotext.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 6
  show_reading_time = true
  mainSections = ["posts"]

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/normankev141"
label = "Twitter"
[[params.ananke_socials]]
name = "linkedin"
url = "https://linkedin.com/in/kevin-norman"
label = "LinkedIn"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/kn100"
label = "Github"
[[params.ananke_socials]]
name = "wloss"
url = "https://kn100.me/weight-loss/"
label = "Body Metrics"

