#!/bin/sh
USER=kn100
HOST="[202.61.250.255]"
DIR=sites/blog   # might sometimes be empty!

HUGO_ENV=production hugo && rsync -avz --delete public/ ${USER}@${HOST}:~/${DIR}
rsync -avz weight-loss/ ${USER}@${HOST}:~/${DIR}/weight-loss

exit 0
